spring.application.name=CounsellorPortal


spring.datasource.url=jdbc:mysql://localhost:3306/manojdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=mysql123


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update



jwt.secret=1CMxaslDK+ml3LGfNxshFYKrZLGLZUapB/XxVVb3Dtw=